name: CrowClicker

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Copy gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      
      - name: Run Test Suite
      - run: ./gradlew test
      
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: app/build/reports
        if: always()
